name: Passagens Salvador

on: 
   workflow_dispatch:
   schedule:
      - cron: '0 8,16,22,3 * * *'

jobs:
  run_automation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependecies
      env:
        PYTHON_VERSION: "3.10"
      run: |
        py_version=$PYTHON_VERSION
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository -y ppa:deadsnakes/ppa
        sudo apt update
        sudo apt install python"$py_version"
        sudo apt install -y nodejs
    - name: Verify Version
      run: |
          python --version
          nodejs -v
          npm --version
          aws --version
    - name: Install libraries for robot
      run: |
          pip install -U pip
          pip install selenium==4.9.1
          pip install -r requirements.txt
          
    - name: Run Tests
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 3
        shell: pwsh
        command: |
            robot -d results -v FROM:São_Paulo -v TO:salvador_brasil -v DEPARTURE:25_janeiro_2025 -v ARRIVAL:4_fevereiro_2025 -v DIAS:5 -v AMPLITUDE:medio  test-cases 
            
    - name: Upload test results
      uses:  actions/upload-artifact@v3.2.1-node20
      if: always()
      with:
        name: reports
        path: valores2.md  
    
    - uses: dtinth/markdown-report-action@v1.0.0
      name: create report from markdown
      with:
               title: reports
               body-file: valores2.md
               
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
          to: -4022243374
          token: 6549097027:AAGZAs99MkBOgpaQLvq3V0rO-7TimDEoMw0
          message: Pesquisa de passagens realizada com sucesso! 
          message_file: valores2.md
          parse_mode: None
          format: None 
